# Datasource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/talos
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update

# Server properties
server:
  display-name: talos # Display name of the application.
  port: 8080
  tomcat:
    max-threads: 400
    compression: on
    compressableMimeTypes: application/json
  error:
    include-stacktrace: never # When to include a "stacktrace" attribute.
    path: /error # Path of the error controller.
    whitelabel.enabled: true # Enable the default error page displayed in browsers in case of a server error.

# Web specific properties
api:
  basepath: /api/v1